# 課題5 テキストデータ分析
配点
- Q1, 1P
- Q2.1, 0.5P
- Q2.2, 0.5P
- Q2.3, 1P
- Q3.1, 1P
- Q3.2, 2P
- Q3.3, 2P
- Q4, 2P

## Q1

$n$-次元ベクトル空間における、任意の2つのベクトル、$ \vec{x}=(x_1,x_2,...,x_n)$、$\vec{y}=(y_1,y_2,...,y_n)$、の間のcos類似度 $cos( \vec{x}, \vec{y})$ は以下のように定義されます。

$cos( \vec{x}, \vec{y}) =  \frac{\vec{x}\cdot \vec{y}}{\|x\|_2\|y\|_2}=\frac{\Sigma^{n}_{i=1}{x_{i}y_{i}}}{\sqrt{\Sigma^{n}_{i=1}x_{i}^{2}}\sqrt{\Sigma^{n}_{i=1}y_{i}^{2}}}$

入力ベクトル $\vec{x}$, $\vec{y}$ をそれぞれ`NumPy` の配列として引数で受け取り、それらのベクトル間のcos類似度を計算して返す関数 `cos_sim` を完成させてください。

In [1]:
import numpy as np

In [32]:
def cos_sim(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

In [2]:
'''
def cos_sim(vec1, vec2):
    v1_sum = 0
    v2_sum = 0
    for i in range(2):
        v1_sum += vec1[i]**2
        v2_sum += vec2[i]**2
    return np.dot(vec1, vec2) / ((v1_sum**0.5)*(v2_sum**0.5))# (vec1とvec2の内積)/np.sqrt(vec1の要素の二乗和*vec2の要素の二乗和)
'''

`cos_sim()`関数が完成したら、以下のセルを実行して動作を確認してください。`-1.0, 1.0, 0.0`がそれぞれのcos類似度です。

In [33]:
print(cos_sim(np.array([1,0]), np.array([-1,0])))
print(cos_sim(np.array([1,0]), np.array([1,0])))
print(cos_sim(np.array([1,0]), np.array([0,-1])))

-1.0
1.0
0.0


## Q2
"course_list.csv"ファイルには以下のように各行に授業名のテキストデータ（文字コードはUTF8）が含まれています。以下では、このファイルを読み込み、各授業のベクトルを作成し、授業間の類似度を求めるコードを実装します。
```Python
## course_list.csvファイル
...
計量経済学Ⅰ
数理統計
計量経済学
経済史Ⅱ
ICTマネジメントⅠ
現代日本経済史
経済学史
...
```
まず必要なモジュールをimportします。

In [4]:
import json
import csv
import numpy as np
import pandas as pd

### Q2.1
"course_list.csv"ファイルを1行ずつ**順番に**読み込み、その各行を要素とするリストを作成して返す`course_list`関数を完成さてください。作成されたリストは変数`courses`で受け取ります。以降の処理では、リスト`courses`のインデックスをその要素（授業名）のIDとして扱います。


In [5]:
def course_list():
    lst=[]
    with open('course_list.csv', 'r',  encoding="utf-8") as f:
        dataReader = csv.reader(f)
        for row in dataReader:
            lst.append(row[0])# lstにrow[0]を追加
    return lst
courses = course_list()

`course_list`関数が完成したら、以下のセルを実行して動作を確認してください。リストの長さ（授業の数）は`4678`、"Pythonプログラミング
入門"授業のID（リスト`courses`のインデックス）は`6`となります。

In [6]:
print(len(courses))
print(course_list().index('Pythonプログラミング入門'))

4678
6


### Q2.2
"keyword_list.csv"ファイルには以下のように各行に1単語が含まれています（文字コードはUTF8）。
```Python
## keyword_list.csvファイル
...
資源
広域
フランス語
語学
教育法
環境学
相関
解析学
森林
...
```
"keywor_list.csv"ファイルを1行ずつ**順番に**読み込み、その各行を要素とするリストを作成して返す`vocab_list`関数を完成さてください。作成されたリストは変数`vocab`で受け取ります。以降の処理では、リスト`vocab`のインデックスをその要素（単語）のIDとして扱います。リスト`vocab`は以降の処理における語彙となります。

In [7]:
def vocab_list():
    lst = []
    with open('keyword_list.csv', 'r',  encoding="utf-8") as f:
        dataReader = csv.reader(f)
        for row in dataReader:
            lst.append(row[0])
    return lst
vocab = vocab_list()

`vocab_list`関数が完成したら、以下のセルを実行して動作を確認してください。リストの長さ（単語の数）は`910`、単語"プログラミング"のID（リスト`vocab`のインデックス）は`113`となります。

In [8]:
print(len(vocab))
print(vocab.index('プログラミング'))

910
113


### Q2.3
リスト`courses`と`vocab`を引数で受け取り、単語のID（リスト`vocab`のその単語のインデックス）をキー、その単語のDF（Document Frequency)を値とする辞書を作成して返す`count_df`関数を作成してください。作成された辞書は変数`df`で受け取ります。この場合、ある単語のDFはその単語を授業名に含む授業数に対応します。**単語が授業名に複数回含まれる場合でも1回と数えます**

In [9]:
def count_df(courses, vocab): #Document Frequency
    dic={}
    for i in range(len(vocab)):
        for course in courses:
            if vocab[i] in course: #courseがvocab[i]を含むという条件:
                if not i in dic:
                    dic[i] = 0
                dic[i] += 1 #dic[i]を1つ増やす
                #dicにiのキーがまだない場合に注意
    return dic
df = count_df(courses, vocab)

`count_df`関数が完成したら、以下のセルを実行して動作を確認してください。辞書の長さは`910`、単語"プログラミング"（IDは`113`）のDFは`23`、単語"英語"（IDは`15`）のDFは`145`となります。

In [10]:
print(len(df))
print(vocab.index('プログラミング'), df[vocab.index('プログラミング')])
print(vocab.index('英語'), df[vocab.index('英語')])

910
113 23
15 145


## Q3
### Q3.1
リスト`vocab`の各単語を次元とする授業ベクトルを考えます。授業ベクトルの長さはリスト`vocab`の長さと等しく、リスト`vocab`のインデックス`i`の単語`vocab[i]`が授業名に含まれる時、授業ベクトルの`i`番目の要素は`1`、含まれなければ`0`とします。

以下では、リスト`courses`と`vocab`を引数で受け取り、リスト`courses`の各授業のベクトルを行、リスト`vocab`の各単語を列とした`NumPy`の行列を作成して返す`lec_word_matrix`関数を完成させてください。作成した授業-単語行列は、授業（行）の授業名に単語（列）が含まれていれば、その要素が1であるような行列です。

In [11]:
# document-term matrix
def lec_word_matrix(courses, vocab):
    mat = np.zeros((len(courses), len(vocab))) #授業数x単語数の0要素の行列を初期化
    for i in range(len(courses)):
        for j in range(len(vocab)):
            if vocab[j] in courses[i]:#courses[i]がvocab[i]を含むという条件:
                mat[i, j] = 1# mat[i, j]に1を代入
    return mat

`lec_word_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した授業-単語行列の要素の値の和は`17406`となります。

In [12]:
np.sum(lec_word_matrix(courses, vocab))

17406.0

### Q3.2
Q3.1で作成した授業-単語行列の各要素を、その授業の授業名に単語が含まれるか否かの1or0ではなく、その授業の授業名に単語が何回含まれるか（TF: Term Frequency)で表した行列を作成して返す`lec_word_tf_matrix`関数を完成させてください。

In [13]:
# document-term matrix
def lec_word_tf_matrix(courses, vocab):
    mat = np.zeros((len(courses), len(vocab))) # 授業数x単語数の0要素の行列を初期化
    for i in range(len(courses)):
        for j in range(len(vocab)):
            if vocab[j] in courses[i]:# courses[i]がvocab[i]を含むという条件:
                 mat[i, j] = courses[i].count(vocab[j])# courses[i]に含まれるvocab[j]の数（ヒント count())をmat[i, j]に代入
    return mat

`lec_word_tf_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した授業-単語行列の要素の値の和は`17732`となります。

In [14]:
np.sum(lec_word_tf_matrix(courses, vocab))

17732.0

授業「総合社会科学高度教養（計量社会科学研究）」には「科学」が2回含まれるので対応する行列の要素の値は2となります。

In [15]:
lec_word_tf_matrix(courses, vocab)[courses.index('総合社会科学高度教養（計量社会科学研究）'), vocab.index('科学')]

2.0

### Q3.3
Q3.2で作成した授業-単語行列の各要素（授業`i`の単語`j`の$TF_{ij}$）にその単語のIDF値を掛けたTFIDF値を要素とする行列を作成して返す`lec_word_tfidf_matrix`関数を完成させてください。作成した行列は変数`tfidf_matrix`で受け取ります。

ここで、授業`i`、単語`j`のTFIDF値は以下のように定義されます。
```Python
TFIDF=TF_ij*log(すべての授業数/単語jのDF)=TF_ij*log(len(courses)/df[j])
```
`log`の計算には`np.log()`を使用してよいです。

`lec_word_tfidf_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した授業-単語行列の要素の値の和の整数部分は`76994`となります。

In [16]:
def lec_word_tfidf_matrix(courses, vocab, df):
    ### 引数:
    # courses: 授業リスト
    # vocab: 単語リスト
    # df: DF辞書
    df = count_df(courses, vocab)
    TF_ij = lec_word_tf_matrix(courses, vocab) #Q3.2で作成した授業-単語行列の各要素（授業iの単語jの 𝑇𝐹𝑖𝑗)
    tfidf_matrix = np.zeros((len(courses), len(vocab))) 
    for i in range(len(courses)):
        for j in range(len(vocab)):
            # その単語のIDF値 = np.log(len(courses)/df[j])
            tfidf_matrix[i, j] = TF_ij[i, j]*np.log(len(courses)/df[j])
    ###  Q3.2のmat[i,j]を"授業名iの単語jのTFIDF値"とした行列を作成するコード ###
    return tfidf_matrix### 上記で作成した行列を返す ###
tfidf_matrix = lec_word_tfidf_matrix(courses, vocab, df)

`lec_word_tfidf_matrix`関数が完成したら、以下のセルを実行して動作を確認してください。作成した授業-単語行列の要素の値の和の整数部分は`76994`となります。

In [17]:
np.sum(lec_word_tfidf_matrix(courses, vocab, df))
#np.sum(tfidf_matrix)

76994.09284193128

授業「総合社会科学高度教養（計量社会科学研究）」には「科学」が`2`回含まれ、「科学」のDF値は`412`なので対応する行列の要素の値は$2*log(4678/412)\simeq4.85$となります。

In [18]:
print(df[vocab.index('科学')])
print(tfidf_matrix[courses.index('総合社会科学高度教養（計量社会科学研究）'), vocab.index('科学')])

412
4.859205195589196


## Q4
Q3.3で作成した授業-単語行列を元に、入力の授業に対してcos類似度に基づいて他のすべての授業との類似度を計算し、類似する授業名をキー、その類似度を値とした辞書を返す以下の`find_similar_course`関数を完成させてください。その際、入力の授業および類似度が0の授業は辞書に含めないようにしてください。cos類似度の計算にはQ1で作成した関数を使ってもよいです。

In [29]:
def find_similar_course(target, tfidf_matrix, courses):
    ### 引数：
    # target:  入力授業のID
    # tfidf_matrix: Q3.3で作成した授業-単語行列
    # courses: 授業リスト    
    ### 入力授業のベクトルtfidf_matrix[target]と各授業iのベクトルtfidf_matrix[i]の類似度を計算するコード ###
    dic_cos = {}
    for i in range(len(courses)):
        if cos_sim(np.array(tfidf_matrix[target]), np.array(tfidf_matrix[i])) != 0:
            dic_cos[courses[i]] = cos_sim(np.array(tfidf_matrix[target]), np.array(tfidf_matrix[i]))
    return dic_cos ### 類似する授業名をキー、その類似度を値とする辞書を返す ###

`find_similar_course`関数が完成したら、以下のセルを実行して動作を確認してください。入力の授業`再生可能エネルギーと公共政策`に類似した上位の授業は、`公共政策、金融市場と公共政策、文化人類学特殊演習（公共政策論）、エネルギー政策、河川流域の環境とその再生、...`となります。

In [34]:
import sys
title="再生可能エネルギーと公共政策" # 入力の授業名
results=find_similar_course(courses.index(title), tfidf_matrix, courses) # 類似授業の辞書を受け取る
df=pd.DataFrame(list(results.items()), columns=['title', "similarity"]) # 類似度が上位の授業を表示
df.sort_values(by='similarity', ascending=False).head(10)

title  similarity
3     再生可能エネルギーと公共政策    1.000000
27              公共政策    0.649841
4          金融市場と公共政策    0.483719
31  文化人類学特殊演習（公共政策論）    0.475690
1            エネルギー政策    0.442935
63      河川流域の環境とその再生    0.413535
46       エネルギー・資源政策論    0.366721
13          発生・再生生物学    0.303553
62             公共経営学    0.277481
57         エネルギー変換工学    0.267711